{
  try {
    runTest();
    isSucceeded=true;
  }
 catch (  Exception e) {
    testException=e;
  }
catch (  AssertionError e) {
    testException=e;
  }
}
