@unittest2.expectedFailure
def test_pickle(self):
    for Klass in (MagicMock, Mock, Subclass, NonCallableMagicMock):
        mock = Klass(name='foo', attribute=3)
        mock.foo(1, 2, 3)
        data = pickle.dumps(mock)
        new = pickle.loads(data)
        new.foo.assert_called_once_with(1, 2, 3)
        self.assertFalse(new.called)
        self.assertTrue(is_instance(new, Klass))
        self.assertIsInstance(new, Thing)
        self.assertIn('name="foo"', repr(new))
        self.assertEqual(new.attribute, 3)
